import type { SourceFieldDefinition } from '../source.interface';

export const QBO_FIELD_DEFINITIONS: Record<string, SourceFieldDefinition[]> = {
  qbo_invoice: [
    { key: 'id',                  label: 'QBO ID',               group: 'Header',  dataType: 'string' },
    { key: 'doc_number',          label: 'Invoice Number',        group: 'Header',  dataType: 'string',  example: 'INV-1001' },
    { key: 'txn_date',            label: 'Transaction Date',      group: 'Dates',   dataType: 'date' },
    { key: 'due_date',            label: 'Due Date',              group: 'Dates',   dataType: 'date' },
    { key: 'customer_name',       label: 'Customer Name',         group: 'Contact', dataType: 'string' },
    { key: 'customer_ref',        label: 'Customer ID (Ref)',     group: 'Contact', dataType: 'string' },
    { key: 'bill_email',          label: 'Billing Email',         group: 'Contact', dataType: 'string' },
    { key: 'currency_code',       label: 'Currency Code',         group: 'Amounts', dataType: 'string' },
    { key: 'exchange_rate',       label: 'Exchange Rate',         group: 'Amounts', dataType: 'decimal' },
    { key: 'total_amt',           label: 'Total Amount',          group: 'Amounts', dataType: 'decimal' },
    { key: 'balance',             label: 'Balance Due',           group: 'Amounts', dataType: 'decimal' },
    { key: 'private_note',        label: 'Memo / Private Note',   group: 'Header',  dataType: 'string' },
    { key: 'line_description',    label: 'Line Description',      group: 'Line',    dataType: 'string' },
    { key: 'line_qty',            label: 'Line Quantity',         group: 'Line',    dataType: 'decimal' },
    { key: 'line_unit_price',     label: 'Line Unit Price',       group: 'Line',    dataType: 'decimal' },
    { key: 'line_amount',         label: 'Line Amount',           group: 'Line',    dataType: 'decimal' },
    { key: 'line_account_ref',    label: 'Line Account ID',       group: 'Line',    dataType: 'string' },
    { key: 'line_account_name',   label: 'Line Account Name',     group: 'Line',    dataType: 'string' },
    { key: 'line_item_ref',       label: 'Line Item ID',          group: 'Line',    dataType: 'string' },
    { key: 'line_item_name',      label: 'Line Item Name',        group: 'Line',    dataType: 'string' },
    { key: 'line_tax_code',       label: 'Line Tax Code',         group: 'Line',    dataType: 'string' },
    { key: 'line_number',         label: 'Line Number',           group: 'Line',    dataType: 'integer' },
  ],

  qbo_bill: [
    { key: 'id',                  label: 'QBO ID',               group: 'Header',  dataType: 'string' },
    { key: 'doc_number',          label: 'Bill Number',          group: 'Header',  dataType: 'string' },
    { key: 'txn_date',            label: 'Bill Date',            group: 'Dates',   dataType: 'date' },
    { key: 'due_date',            label: 'Due Date',             group: 'Dates',   dataType: 'date' },
    { key: 'vendor_name',         label: 'Vendor Name',          group: 'Contact', dataType: 'string' },
    { key: 'vendor_ref',          label: 'Vendor ID (Ref)',      group: 'Contact', dataType: 'string' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts', dataType: 'string' },
    { key: 'total_amt',           label: 'Total Amount',         group: 'Amounts', dataType: 'decimal' },
    { key: 'balance',             label: 'Balance Due',          group: 'Amounts', dataType: 'decimal' },
    { key: 'private_note',        label: 'Memo',                 group: 'Header',  dataType: 'string' },
    { key: 'line_description',    label: 'Line Description',     group: 'Line',    dataType: 'string' },
    { key: 'line_amount',         label: 'Line Amount',          group: 'Line',    dataType: 'decimal' },
    { key: 'line_account_ref',    label: 'Line Account ID',      group: 'Line',    dataType: 'string' },
    { key: 'line_account_name',   label: 'Line Account Name',    group: 'Line',    dataType: 'string' },
    { key: 'line_item_ref',       label: 'Line Item ID',         group: 'Line',    dataType: 'string' },
    { key: 'line_item_name',      label: 'Line Item Name',       group: 'Line',    dataType: 'string' },
    { key: 'line_number',         label: 'Line Number',          group: 'Line',    dataType: 'integer' },
  ],

  qbo_payment: [
    { key: 'id',                  label: 'QBO ID',               group: 'Header',  dataType: 'string' },
    { key: 'payment_ref_num',     label: 'Payment Reference',    group: 'Header',  dataType: 'string' },
    { key: 'txn_date',            label: 'Payment Date',         group: 'Dates',   dataType: 'date' },
    { key: 'customer_name',       label: 'Customer Name',        group: 'Contact', dataType: 'string' },
    { key: 'customer_ref',        label: 'Customer ID',          group: 'Contact', dataType: 'string' },
    { key: 'total_amt',           label: 'Amount',               group: 'Amounts', dataType: 'decimal' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts', dataType: 'string' },
    { key: 'exchange_rate',       label: 'Exchange Rate',        group: 'Amounts', dataType: 'decimal' },
    { key: 'deposit_to_account',  label: 'Deposited To Account', group: 'Account', dataType: 'string' },
    { key: 'private_note',        label: 'Memo',                 group: 'Header',  dataType: 'string' },
  ],

  qbo_journal_entry: [
    { key: 'id',                  label: 'QBO ID',               group: 'Header',  dataType: 'string' },
    { key: 'doc_number',          label: 'Journal Number',       group: 'Header',  dataType: 'string' },
    { key: 'txn_date',            label: 'Transaction Date',     group: 'Dates',   dataType: 'date' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts', dataType: 'string' },
    { key: 'exchange_rate',       label: 'Exchange Rate',        group: 'Amounts', dataType: 'decimal' },
    { key: 'narration',           label: 'Narration / Memo',     group: 'Header',  dataType: 'string' },
    { key: 'line_description',    label: 'Line Description',     group: 'Line',    dataType: 'string' },
    { key: 'line_amount',         label: 'Line Amount',          group: 'Line',    dataType: 'decimal' },
    { key: 'line_posting_type',   label: 'Posting Type',         group: 'Line',    dataType: 'string',  description: 'Debit or Credit' },
    { key: 'line_account_ref',    label: 'Account ID',           group: 'Line',    dataType: 'string' },
    { key: 'line_account_name',   label: 'Account Name',         group: 'Line',    dataType: 'string' },
    { key: 'line_entity_type',    label: 'Entity Type',          group: 'Line',    dataType: 'string',  description: 'Customer, Vendor, Employee etc.' },
    { key: 'line_entity_name',    label: 'Entity Name',          group: 'Line',    dataType: 'string' },
    { key: 'line_number',         label: 'Line Number',          group: 'Line',    dataType: 'integer' },
  ],

  qbo_vendor: [
    { key: 'id',                  label: 'QBO ID',               group: 'Identity', dataType: 'string' },
    { key: 'display_name',        label: 'Display Name',         group: 'Identity', dataType: 'string' },
    { key: 'company_name',        label: 'Company Name',         group: 'Identity', dataType: 'string' },
    { key: 'print_on_check_name', label: 'Print on Check Name',  group: 'Identity', dataType: 'string' },
    { key: 'given_name',          label: 'First Name',           group: 'Identity', dataType: 'string' },
    { key: 'family_name',         label: 'Last Name',            group: 'Identity', dataType: 'string' },
    { key: 'email',               label: 'Email',                group: 'Contact',  dataType: 'string' },
    { key: 'phone',               label: 'Phone',                group: 'Contact',  dataType: 'string' },
    { key: 'vendor_1099',         label: '1099 Eligible',        group: 'Tax',      dataType: 'boolean' },
    { key: 'acct_num',            label: 'Account Number',       group: 'Tax',      dataType: 'string' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts',  dataType: 'string' },
    { key: 'balance',             label: 'Balance',              group: 'Amounts',  dataType: 'decimal' },
    { key: 'bill_addr_line1',     label: 'Address Line 1',       group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_city',      label: 'City',                 group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_country',   label: 'Country',              group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_postal_code',label:'Postal Code',          group: 'Address',  dataType: 'string' },
  ],

  qbo_customer: [
    { key: 'id',                  label: 'QBO ID',               group: 'Identity', dataType: 'string' },
    { key: 'display_name',        label: 'Display Name',         group: 'Identity', dataType: 'string' },
    { key: 'company_name',        label: 'Company Name',         group: 'Identity', dataType: 'string' },
    { key: 'given_name',          label: 'First Name',           group: 'Identity', dataType: 'string' },
    { key: 'family_name',         label: 'Last Name',            group: 'Identity', dataType: 'string' },
    { key: 'email',               label: 'Email',                group: 'Contact',  dataType: 'string' },
    { key: 'phone',               label: 'Phone',                group: 'Contact',  dataType: 'string' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts',  dataType: 'string' },
    { key: 'balance',             label: 'Open Balance',         group: 'Amounts',  dataType: 'decimal' },
    { key: 'bill_addr_line1',     label: 'Address Line 1',       group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_city',      label: 'City',                 group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_country_sub_division_code', label: 'State / Region', group: 'Address', dataType: 'string' },
    { key: 'bill_addr_postal_code',label:'Postal Code',          group: 'Address',  dataType: 'string' },
    { key: 'bill_addr_country',   label: 'Country',              group: 'Address',  dataType: 'string' },
    { key: 'notes',               label: 'Notes',                group: 'Other',    dataType: 'string' },
  ],

  qbo_item: [
    { key: 'id',                  label: 'QBO ID',               group: 'Identity', dataType: 'string' },
    { key: 'name',                label: 'Name',                 group: 'Identity', dataType: 'string' },
    { key: 'sku',                 label: 'SKU',                  group: 'Identity', dataType: 'string' },
    { key: 'description',         label: 'Description',          group: 'Sales',    dataType: 'string' },
    { key: 'type',                label: 'Type',                 group: 'Identity', dataType: 'string', description: 'Inventory, Service, NonInventory' },
    { key: 'unit_price',          label: 'Unit Price',           group: 'Sales',    dataType: 'decimal' },
    { key: 'purchase_cost',       label: 'Purchase Cost',        group: 'Purchasing', dataType: 'decimal' },
    { key: 'income_account_ref',  label: 'Income Account ID',    group: 'Sales',    dataType: 'string' },
    { key: 'income_account_name', label: 'Income Account Name',  group: 'Sales',    dataType: 'string' },
    { key: 'expense_account_ref', label: 'Expense Account ID',   group: 'Purchasing', dataType: 'string' },
    { key: 'qty_on_hand',         label: 'Quantity on Hand',     group: 'Inventory', dataType: 'decimal' },
    { key: 'active',              label: 'Active',               group: 'Identity', dataType: 'boolean' },
  ],
};
