import type { SourceFieldDefinition } from '../source.interface';

// ── Shared header fields (invoices & bills) ───────────────────────────────────

const INVOICE_HEADER: SourceFieldDefinition[] = [
  { key: 'invoice_id',            label: 'Invoice ID',            group: 'Header',  dataType: 'string',  description: 'Xero internal GUID for the invoice' },
  { key: 'invoice_number',        label: 'Invoice Number',        group: 'Header',  dataType: 'string',  example: 'INV-0001' },
  { key: 'reference',             label: 'Reference',             group: 'Header',  dataType: 'string',  example: 'PO-12345' },
  { key: 'type',                  label: 'Type',                  group: 'Header',  dataType: 'string',  description: 'ACCREC (AR) or ACCPAY (AP)' },
  { key: 'status',                label: 'Status',                group: 'Header',  dataType: 'string',  example: 'AUTHORISED' },
  { key: 'contact_id',            label: 'Contact ID',            group: 'Contact', dataType: 'string' },
  { key: 'contact_name',          label: 'Contact Name',          group: 'Contact', dataType: 'string',  example: 'Acme Ltd' },
  { key: 'contact_email',         label: 'Contact Email',         group: 'Contact', dataType: 'string' },
  { key: 'contact_account_number',label: 'Contact Account Number',group: 'Contact', dataType: 'string' },
  { key: 'date',                  label: 'Invoice Date',          group: 'Dates',   dataType: 'date',    example: '2024-01-15' },
  { key: 'due_date',              label: 'Due Date',              group: 'Dates',   dataType: 'date' },
  { key: 'currency_code',         label: 'Currency Code',         group: 'Amounts', dataType: 'string',  example: 'GBP' },
  { key: 'currency_rate',         label: 'Currency Rate',         group: 'Amounts', dataType: 'decimal' },
  { key: 'sub_total',             label: 'Sub Total',             group: 'Amounts', dataType: 'decimal' },
  { key: 'total_tax',             label: 'Total Tax',             group: 'Amounts', dataType: 'decimal' },
  { key: 'total',                 label: 'Total',                 group: 'Amounts', dataType: 'decimal' },
  { key: 'amount_due',            label: 'Amount Due',            group: 'Amounts', dataType: 'decimal' },
  { key: 'amount_paid',           label: 'Amount Paid',           group: 'Amounts', dataType: 'decimal' },
];

const LINE_FIELDS: SourceFieldDefinition[] = [
  { key: 'line_item_id',          label: 'Line Item ID',          group: 'Line',    dataType: 'string' },
  { key: 'line_description',      label: 'Line Description',      group: 'Line',    dataType: 'string' },
  { key: 'line_quantity',         label: 'Line Quantity',         group: 'Line',    dataType: 'decimal' },
  { key: 'line_unit_amount',      label: 'Line Unit Amount',      group: 'Line',    dataType: 'decimal' },
  { key: 'line_account_code',     label: 'Line Account Code',     group: 'Line',    dataType: 'string',  example: '200' },
  { key: 'line_account_name',     label: 'Line Account Name',     group: 'Line',    dataType: 'string' },
  { key: 'line_item_code',        label: 'Line Item Code',        group: 'Line',    dataType: 'string' },
  { key: 'line_tax_type',         label: 'Line Tax Type',         group: 'Line',    dataType: 'string',  example: 'OUTPUT2' },
  { key: 'line_tax_amount',       label: 'Line Tax Amount',       group: 'Line',    dataType: 'decimal' },
  { key: 'line_amount',           label: 'Line Amount (net)',     group: 'Line',    dataType: 'decimal' },
  { key: 'line_tracking_name',    label: 'Tracking Category',     group: 'Line',    dataType: 'string' },
  { key: 'line_tracking_option',  label: 'Tracking Option',       group: 'Line',    dataType: 'string' },
  { key: 'line_number',           label: 'Line Number',           group: 'Line',    dataType: 'integer', description: '1-based position within the document' },
];

export const XERO_FIELD_DEFINITIONS: Record<string, SourceFieldDefinition[]> = {
  xero_invoice: [...INVOICE_HEADER, ...LINE_FIELDS],
  xero_bill:    [...INVOICE_HEADER, ...LINE_FIELDS],

  xero_credit_note: [
    { key: 'credit_note_id',     label: 'Credit Note ID',     group: 'Header',  dataType: 'string' },
    { key: 'credit_note_number', label: 'Credit Note Number', group: 'Header',  dataType: 'string' },
    { key: 'reference',          label: 'Reference',          group: 'Header',  dataType: 'string' },
    { key: 'type',               label: 'Type',               group: 'Header',  dataType: 'string' },
    { key: 'status',             label: 'Status',             group: 'Header',  dataType: 'string' },
    { key: 'contact_id',         label: 'Contact ID',         group: 'Contact', dataType: 'string' },
    { key: 'contact_name',       label: 'Contact Name',       group: 'Contact', dataType: 'string' },
    { key: 'date',               label: 'Date',               group: 'Dates',   dataType: 'date' },
    { key: 'currency_code',      label: 'Currency Code',      group: 'Amounts', dataType: 'string' },
    { key: 'sub_total',          label: 'Sub Total',          group: 'Amounts', dataType: 'decimal' },
    { key: 'total_tax',          label: 'Total Tax',          group: 'Amounts', dataType: 'decimal' },
    { key: 'total',              label: 'Total',              group: 'Amounts', dataType: 'decimal' },
    { key: 'remaining_credit',   label: 'Remaining Credit',   group: 'Amounts', dataType: 'decimal' },
    ...LINE_FIELDS,
  ],

  xero_payment: [
    { key: 'payment_id',        label: 'Payment ID',          group: 'Header',  dataType: 'string' },
    { key: 'type',              label: 'Type',                group: 'Header',  dataType: 'string', description: 'ACCRECPAYMENT or ACCPAYPAYMENT' },
    { key: 'status',            label: 'Status',              group: 'Header',  dataType: 'string' },
    { key: 'reference',         label: 'Reference',           group: 'Header',  dataType: 'string' },
    { key: 'payment_date',      label: 'Payment Date',        group: 'Dates',   dataType: 'date' },
    { key: 'amount',            label: 'Amount',              group: 'Amounts', dataType: 'decimal' },
    { key: 'currency_code',     label: 'Currency Code',       group: 'Amounts', dataType: 'string' },
    { key: 'currency_rate',     label: 'Currency Rate',       group: 'Amounts', dataType: 'decimal' },
    { key: 'bank_account_code', label: 'Bank Account Code',   group: 'Account', dataType: 'string' },
    { key: 'bank_account_name', label: 'Bank Account Name',   group: 'Account', dataType: 'string' },
    { key: 'invoice_number',    label: 'Applied Invoice No.', group: 'Invoice', dataType: 'string' },
    { key: 'invoice_id',        label: 'Applied Invoice ID',  group: 'Invoice', dataType: 'string' },
    { key: 'contact_name',      label: 'Contact Name',        group: 'Contact', dataType: 'string' },
    { key: 'is_reconciled',     label: 'Reconciled',          group: 'Status',  dataType: 'boolean' },
  ],

  xero_journal: [
    { key: 'journal_id',        label: 'Journal ID',          group: 'Header',  dataType: 'string' },
    { key: 'journal_number',    label: 'Journal Number',      group: 'Header',  dataType: 'integer' },
    { key: 'narration',         label: 'Narration',           group: 'Header',  dataType: 'string' },
    { key: 'date',              label: 'Journal Date',        group: 'Dates',   dataType: 'date' },
    { key: 'reference',         label: 'Reference',           group: 'Header',  dataType: 'string' },
    { key: 'show_on_cash_basis',label: 'Show on Cash Basis',  group: 'Header',  dataType: 'boolean' },
    { key: 'line_account_code', label: 'Account Code',        group: 'Line',    dataType: 'string' },
    { key: 'line_account_name', label: 'Account Name',        group: 'Line',    dataType: 'string' },
    { key: 'line_account_type', label: 'Account Type',        group: 'Line',    dataType: 'string' },
    { key: 'line_description',  label: 'Line Description',    group: 'Line',    dataType: 'string' },
    { key: 'line_net_amount',   label: 'Net Amount',          group: 'Line',    dataType: 'decimal', description: 'Positive = debit, negative = credit' },
    { key: 'line_gross_amount', label: 'Gross Amount',        group: 'Line',    dataType: 'decimal' },
    { key: 'line_tax_amount',   label: 'Tax Amount',          group: 'Line',    dataType: 'decimal' },
    { key: 'line_tax_type',     label: 'Tax Type',            group: 'Line',    dataType: 'string' },
    { key: 'line_is_net',       label: 'Is Net Amount',       group: 'Line',    dataType: 'boolean' },
    { key: 'line_tracking_name',label: 'Tracking Category',   group: 'Line',    dataType: 'string' },
    { key: 'line_number',       label: 'Line Number',         group: 'Line',    dataType: 'integer' },
  ],

  xero_contact: [
    { key: 'contact_id',          label: 'Contact ID',         group: 'Identity', dataType: 'string' },
    { key: 'name',                label: 'Name',               group: 'Identity', dataType: 'string' },
    { key: 'account_number',      label: 'Account Number',     group: 'Identity', dataType: 'string' },
    { key: 'tax_number',          label: 'Tax Number / VAT',   group: 'Identity', dataType: 'string' },
    { key: 'email',               label: 'Email',              group: 'Contact',  dataType: 'string' },
    { key: 'phone',               label: 'Phone',              group: 'Contact',  dataType: 'string' },
    { key: 'is_customer',         label: 'Is Customer',        group: 'Type',     dataType: 'boolean' },
    { key: 'is_supplier',         label: 'Is Supplier',        group: 'Type',     dataType: 'boolean' },
    { key: 'contact_status',      label: 'Status',             group: 'Type',     dataType: 'string' },
    { key: 'address_line1',       label: 'Address Line 1',     group: 'Address',  dataType: 'string' },
    { key: 'address_line2',       label: 'Address Line 2',     group: 'Address',  dataType: 'string' },
    { key: 'city',                label: 'City',               group: 'Address',  dataType: 'string' },
    { key: 'region',              label: 'Region / County',    group: 'Address',  dataType: 'string' },
    { key: 'postal_code',         label: 'Postal Code',        group: 'Address',  dataType: 'string' },
    { key: 'country',             label: 'Country',            group: 'Address',  dataType: 'string' },
    { key: 'bank_account_number', label: 'Bank Account',       group: 'Banking',  dataType: 'string' },
    { key: 'bank_account_name',   label: 'Bank Account Name',  group: 'Banking',  dataType: 'string' },
  ],

  xero_item: [
    { key: 'item_id',         label: 'Item ID',          group: 'Header',  dataType: 'string' },
    { key: 'code',            label: 'Item Code',        group: 'Header',  dataType: 'string' },
    { key: 'name',            label: 'Name',             group: 'Header',  dataType: 'string' },
    { key: 'description',     label: 'Description',      group: 'Header',  dataType: 'string' },
    { key: 'purchase_description', label: 'Purchase Description', group: 'Purchasing', dataType: 'string' },
    { key: 'is_tracked',      label: 'Is Tracked',       group: 'Inventory', dataType: 'boolean' },
    { key: 'is_sold',         label: 'Is Sold',          group: 'Sales',   dataType: 'boolean' },
    { key: 'is_purchased',    label: 'Is Purchased',     group: 'Purchasing', dataType: 'boolean' },
    { key: 'sales_price',     label: 'Sales Price',      group: 'Sales',   dataType: 'decimal' },
    { key: 'sales_account',   label: 'Sales Account Code', group: 'Sales', dataType: 'string' },
    { key: 'purchase_price',  label: 'Purchase Price',   group: 'Purchasing', dataType: 'decimal' },
    { key: 'purchase_account',label: 'Purchase Account Code', group: 'Purchasing', dataType: 'string' },
    { key: 'quantity_on_hand',label: 'Quantity on Hand', group: 'Inventory', dataType: 'decimal' },
  ],
};
