import type { SourceFieldDefinition } from '../source.interface';

export const SAGE50_FIELD_DEFINITIONS: Record<string, SourceFieldDefinition[]> = {
  sage50_sales_invoice: [
    { key: 'id',                  label: 'Record ID',            group: 'Header',  dataType: 'string' },
    { key: 'invoice_number',      label: 'Invoice Number',       group: 'Header',  dataType: 'string',  example: 'SI-0001' },
    { key: 'reference',           label: 'Reference',            group: 'Header',  dataType: 'string' },
    { key: 'contact_id',          label: 'Contact ID',           group: 'Contact', dataType: 'string' },
    { key: 'contact_name',        label: 'Customer Name',        group: 'Contact', dataType: 'string' },
    { key: 'contact_ref',         label: 'Customer Reference',   group: 'Contact', dataType: 'string' },
    { key: 'date',                label: 'Invoice Date',         group: 'Dates',   dataType: 'date' },
    { key: 'due_date',            label: 'Due Date',             group: 'Dates',   dataType: 'date' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts', dataType: 'string' },
    { key: 'status',              label: 'Status',               group: 'Header',  dataType: 'string' },
    { key: 'net_amount',          label: 'Net Amount',           group: 'Amounts', dataType: 'decimal' },
    { key: 'tax_amount',          label: 'Tax Amount',           group: 'Amounts', dataType: 'decimal' },
    { key: 'total_amount',        label: 'Total Amount',         group: 'Amounts', dataType: 'decimal' },
    { key: 'outstanding_amount',  label: 'Outstanding Amount',   group: 'Amounts', dataType: 'decimal' },
    { key: 'notes',               label: 'Notes',                group: 'Header',  dataType: 'string' },
    { key: 'line_description',    label: 'Line Description',     group: 'Line',    dataType: 'string' },
    { key: 'line_quantity',       label: 'Line Quantity',        group: 'Line',    dataType: 'decimal' },
    { key: 'line_unit_price',     label: 'Line Unit Price',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_net_amount',     label: 'Line Net Amount',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_tax_amount',     label: 'Line Tax Amount',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_total_amount',   label: 'Line Total Amount',    group: 'Line',    dataType: 'decimal' },
    { key: 'line_ledger_account', label: 'Ledger Account Code',  group: 'Line',    dataType: 'string' },
    { key: 'line_ledger_name',    label: 'Ledger Account Name',  group: 'Line',    dataType: 'string' },
    { key: 'line_tax_code',       label: 'Tax Code',             group: 'Line',    dataType: 'string' },
    { key: 'line_number',         label: 'Line Number',          group: 'Line',    dataType: 'integer' },
  ],

  sage50_purchase_invoice: [
    { key: 'id',                  label: 'Record ID',            group: 'Header',  dataType: 'string' },
    { key: 'invoice_number',      label: 'Invoice Number',       group: 'Header',  dataType: 'string' },
    { key: 'reference',           label: 'Reference',            group: 'Header',  dataType: 'string' },
    { key: 'contact_id',          label: 'Contact ID',           group: 'Contact', dataType: 'string' },
    { key: 'contact_name',        label: 'Supplier Name',        group: 'Contact', dataType: 'string' },
    { key: 'contact_ref',         label: 'Supplier Reference',   group: 'Contact', dataType: 'string' },
    { key: 'date',                label: 'Invoice Date',         group: 'Dates',   dataType: 'date' },
    { key: 'due_date',            label: 'Due Date',             group: 'Dates',   dataType: 'date' },
    { key: 'currency_code',       label: 'Currency Code',        group: 'Amounts', dataType: 'string' },
    { key: 'status',              label: 'Status',               group: 'Header',  dataType: 'string' },
    { key: 'net_amount',          label: 'Net Amount',           group: 'Amounts', dataType: 'decimal' },
    { key: 'tax_amount',          label: 'Tax Amount',           group: 'Amounts', dataType: 'decimal' },
    { key: 'total_amount',        label: 'Total Amount',         group: 'Amounts', dataType: 'decimal' },
    { key: 'outstanding_amount',  label: 'Outstanding Amount',   group: 'Amounts', dataType: 'decimal' },
    { key: 'notes',               label: 'Notes',                group: 'Header',  dataType: 'string' },
    { key: 'line_description',    label: 'Line Description',     group: 'Line',    dataType: 'string' },
    { key: 'line_quantity',       label: 'Line Quantity',        group: 'Line',    dataType: 'decimal' },
    { key: 'line_unit_price',     label: 'Line Unit Price',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_net_amount',     label: 'Line Net Amount',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_tax_amount',     label: 'Line Tax Amount',      group: 'Line',    dataType: 'decimal' },
    { key: 'line_total_amount',   label: 'Line Total Amount',    group: 'Line',    dataType: 'decimal' },
    { key: 'line_ledger_account', label: 'Ledger Account Code',  group: 'Line',    dataType: 'string' },
    { key: 'line_ledger_name',    label: 'Ledger Account Name',  group: 'Line',    dataType: 'string' },
    { key: 'line_tax_code',       label: 'Tax Code',             group: 'Line',    dataType: 'string' },
    { key: 'line_number',         label: 'Line Number',          group: 'Line',    dataType: 'integer' },
  ],

  sage50_journal: [
    { key: 'id',                      label: 'Journal ID',            group: 'Header',  dataType: 'string' },
    { key: 'date',                     label: 'Journal Date',          group: 'Dates',   dataType: 'date' },
    { key: 'reference',                label: 'Reference',             group: 'Header',  dataType: 'string' },
    { key: 'description',              label: 'Description / Narration', group: 'Header', dataType: 'string' },
    { key: 'journal_code',             label: 'Journal Code',          group: 'Header',  dataType: 'string' },
    { key: 'currency_code',            label: 'Currency Code',         group: 'Amounts', dataType: 'string' },
    { key: 'line_description',         label: 'Line Description',      group: 'Line',    dataType: 'string' },
    { key: 'line_ledger_account',      label: 'Ledger Account Code',   group: 'Line',    dataType: 'string' },
    { key: 'line_ledger_account_name', label: 'Ledger Account Name',   group: 'Line',    dataType: 'string' },
    { key: 'line_debit',               label: 'Debit Amount',          group: 'Line',    dataType: 'decimal' },
    { key: 'line_credit',              label: 'Credit Amount',         group: 'Line',    dataType: 'decimal' },
    { key: 'line_tax_code',            label: 'Tax Code',              group: 'Line',    dataType: 'string' },
    { key: 'line_number',              label: 'Line Number',           group: 'Line',    dataType: 'integer' },
  ],

  sage50_contact: [
    { key: 'id',              label: 'Contact ID',        group: 'Identity', dataType: 'string' },
    { key: 'name',            label: 'Name',              group: 'Identity', dataType: 'string' },
    { key: 'reference',       label: 'Reference',         group: 'Identity', dataType: 'string' },
    { key: 'contact_type',    label: 'Contact Type',      group: 'Identity', dataType: 'string', description: 'CUSTOMER or SUPPLIER' },
    { key: 'status',          label: 'Status',            group: 'Identity', dataType: 'string' },
    { key: 'email',           label: 'Email',             group: 'Contact',  dataType: 'string' },
    { key: 'phone',           label: 'Phone',             group: 'Contact',  dataType: 'string' },
    { key: 'website',         label: 'Website',           group: 'Contact',  dataType: 'string' },
    { key: 'address_line_1',  label: 'Address Line 1',    group: 'Address',  dataType: 'string' },
    { key: 'address_line_2',  label: 'Address Line 2',    group: 'Address',  dataType: 'string' },
    { key: 'city',            label: 'Town / City',       group: 'Address',  dataType: 'string' },
    { key: 'region',          label: 'County / Region',   group: 'Address',  dataType: 'string' },
    { key: 'postal_code',     label: 'Postal Code',       group: 'Address',  dataType: 'string' },
    { key: 'country',         label: 'Country',           group: 'Address',  dataType: 'string' },
    { key: 'currency_code',   label: 'Currency Code',     group: 'Amounts',  dataType: 'string' },
    { key: 'balance',         label: 'Balance',           group: 'Amounts',  dataType: 'decimal' },
    { key: 'credit_limit',    label: 'Credit Limit',      group: 'Amounts',  dataType: 'decimal' },
    { key: 'tax_number',      label: 'VAT / Tax Number',  group: 'Tax',      dataType: 'string' },
    { key: 'notes',           label: 'Notes',             group: 'Other',    dataType: 'string' },
  ],
};
